- hosts: localhost
  become: true
  pre_tasks:
    - name: Update cache / repos
      apt:
        update_cache: true
      tags:
      - zsh
      - node
  tasks:
  - include: zsh.yml
  - include: node.yml
